import { StudentProfile, TeacherClassStudent, ClassInsight, ParentWeeklyReport } from '../types';

export const INITIAL_STUDENT_PROFILE: StudentProfile = {
  id: 'student-aarav-1',
  name: 'Aarav Sharma',
  age: 14,
  grade: 'Class 9',
  board: 'CBSE',
  subjects: ['Mathematics', 'Science', 'English'],
  targetExam: 'Class 9 Annuals & Class 10 Foundation',
  preferredLanguage: 'en',
  learningGoal: 'Master Class 9 Mathematics & Build Strong Problem Solving Confidence',
  avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80',
  streakDays: 7,
  todayGoal: {
    topic: 'Master Decimals & Word Problems',
    progressPercentage: 78,
    targetMinutes: 25,
    completedMinutes: 18,
  },
};

export const MOCK_CLASS_STUDENTS: TeacherClassStudent[] = [
  {
    id: 's-1',
    name: 'Aarav Sharma',
    avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=100&auto=format&fit=crop&q=80',
    grade: 'Class 9-A',
    overallMastery: 74,
    weakestConcept: 'Decimals in Word Problems',
    statusLight: 'yellow',
    recentMisconception: 'Decimal Representation Bottleneck',
    timeSpentHours: 14.5,
    improvementPercentage: 18,
    attendanceStreak: 7,
    lastActive: '10 mins ago',
    isAtRisk: false,
  },
  {
    id: 's-2',
    name: 'Siya Patel',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=100&auto=format&fit=crop&q=80',
    grade: 'Class 9-A',
    overallMastery: 91,
    weakestConcept: 'None (Excelling)',
    statusLight: 'green',
    recentMisconception: 'None',
    timeSpentHours: 19.2,
    improvementPercentage: 8,
    attendanceStreak: 14,
    lastActive: '2 hours ago',
    isAtRisk: false,
  },
  {
    id: 's-3',
    name: 'Rohan Deshmukh',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop&q=80',
    grade: 'Class 9-A',
    overallMastery: 54,
    weakestConcept: 'Fractions (Denominator Comparison)',
    statusLight: 'red',
    recentMisconception: 'Larger Denominator Fallacy',
    timeSpentHours: 8.0,
    improvementPercentage: 4,
    attendanceStreak: 3,
    lastActive: '1 day ago',
    isAtRisk: true,
  },
  {
    id: 's-4',
    name: 'Ananya Verma',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&auto=format&fit=crop&q=80',
    grade: 'Class 9-A',
    overallMastery: 83,
    weakestConcept: 'Negative Signs in Algebra',
    statusLight: 'green',
    recentMisconception: 'Negative Sign Distribution',
    timeSpentHours: 16.0,
    improvementPercentage: 12,
    attendanceStreak: 9,
    lastActive: '30 mins ago',
    isAtRisk: false,
  },
  {
    id: 's-5',
    name: 'Kabir Khan',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&auto=format&fit=crop&q=80',
    grade: 'Class 9-A',
    overallMastery: 61,
    weakestConcept: 'Fractions Addition',
    statusLight: 'yellow',
    recentMisconception: 'Cross-multiplication confusion',
    timeSpentHours: 11.2,
    improvementPercentage: 9,
    attendanceStreak: 5,
    lastActive: '5 hours ago',
    isAtRisk: false,
  },
  {
    id: 's-6',
    name: 'Priya Iyer',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80',
    grade: 'Class 9-A',
    overallMastery: 88,
    weakestConcept: 'Geometry Theorems',
    statusLight: 'green',
    recentMisconception: 'Angle sum overgeneralization',
    timeSpentHours: 17.8,
    improvementPercentage: 15,
    attendanceStreak: 12,
    lastActive: 'Just now',
    isAtRisk: false,
  },
];

export const MOCK_CLASS_INSIGHTS: ClassInsight[] = [
  {
    id: 'ins-1',
    title: {
      en: 'Denominator Fallacy Cluster Detected',
      hi: 'हर (Denominator) संबंधी भ्रम का समूह पहचाना गया',
      mr: 'छेद गैरसमज गट आढळला',
    },
    affectedStudentCount: 12,
    totalStudents: 32,
    concept: 'Fractions - Comparison',
    detectedMisconception: 'They believe a larger denominator means a larger fraction (e.g., 1/8 > 1/4).',
    severity: 'high',
    recommendedAction: {
      en: 'Run a 15-minute visual fractions bar cutting interactive activity with these 12 students.',
      hi: 'इन 12 छात्रों के साथ 15 मिनट की विजुअल भिन्न पट्टी (Fractions Bar) गतिविधि आयोजित करें।',
      mr: 'या 12 विद्यार्थ्यांसाठी 15 मिनिटांचे व्हिज्युअल अपूर्णांक पट्टी प्रात्यक्षिक घ्या.',
    },
    actionButtonLabel: {
      en: 'Assign 15-Min Visual Activity to 12 Students',
      hi: '12 छात्रों को 15-मिनट की गतिविधि असाइन करें',
      mr: '12 विद्यार्थ्यांना 15-मिनिटांचे प्रात्यक्षिक द्या',
    },
    isActionExecuted: false,
  },
  {
    id: 'ins-2',
    title: {
      en: 'Decimal Word Problem Translation Bottleneck',
      hi: 'दशमलव शाब्दिक प्रश्नों में अनुवाद की समस्या',
      mr: 'दशांश शाब्दिक उदाहरणांमध्ये मांडणीची अडचण',
    },
    affectedStudentCount: 7,
    totalStudents: 32,
    concept: 'Decimals in Applied Contexts',
    detectedMisconception: 'Students add unit rates instead of multiplying by quantity.',
    severity: 'medium',
    recommendedAction: {
      en: 'Deploy the 3-step Rate × Quantity currency visualizer worksheet.',
      hi: '3-चरणीय दर × मात्रा मुद्रा विजुअलाइज़र वर्कशीट असाइन करें।',
      mr: '3 टप्प्यांची दर × प्रमाण विजुअलायझर सराव पत्रिका पाठवा.',
    },
    actionButtonLabel: {
      en: 'Send Socratic Remedial Scaffold',
      hi: 'सुकराती उपचारात्मक सहायता भेजें',
      mr: 'सुकरात उपचारात्मक साहाय्य पाठवा',
    },
    isActionExecuted: false,
  },
];

export const MOCK_PARENT_REPORT: ParentWeeklyReport = {
  studentName: 'Aarav Sharma',
  dateRange: 'Aug 28 – Sep 03, 2026',
  overallProgressDelta: 14,
  strongestArea: 'Algebra & Basic Arithmetic',
  needsAttentionArea: 'Decimals (Word Problems)',
  learningConsistency: {
    completedDays: 5,
    totalDays: 7,
    streakDays: 7,
    dailyMinutes: [25, 30, 20, 0, 35, 25, 30],
  },
  masteryHighlights: [
    {
      concept: 'Multiplication & Tables',
      initialScore: 88,
      currentScore: 92,
      status: 'Mastered',
    },
    {
      concept: 'Fractions Fundamentals',
      initialScore: 74,
      currentScore: 82,
      status: 'Mastered',
    },
    {
      concept: 'Decimals in Word Problems',
      initialScore: 43,
      currentScore: 71,
      status: 'Breakthrough Progress',
    },
  ],
  aiParentAdvice: {
    en: 'Aarav made a huge breakthrough in decimals this week (+28% mastery jump)! He now understands how to translate money and measurement stories into math equations. Encourage him to do 10 minutes of decimal practice tomorrow to solidify retention.',
    hi: 'आरव ने इस सप्ताह दशमलव में बहुत बड़ी छलांग लगाई है (+28% की वृद्धि)! अब वह रुपये-पैसे और माप के शाब्दिक प्रश्नों को आसानी से समीकरण में बदल रहा है। कल उसे 10 मिनट के अभ्यास के लिए प्रेरित करें।',
    mr: 'आरवने या आठवड्यात दशांश संकल्पनेमध्ये मोठी झेप घेतली आहे (+28% वाढ)! त्याला आता दैनंदिन व्यवहार आणि शाब्दिक उदाहरणांचे गणिती रूपांतर करणे छान जमू लागले आहे. उद्या 10 मिनिटे सराव करण्यासाठी त्याला प्रोत्साहन द्या.',
  },
  quickCheckInQuestions: [
    {
      en: 'Ask at dinner: "Aarav, if 1 kg apples is ₹120.50, how much will 2.5 kg cost?" (Notice how he uses his new rate × quantity trick!)',
      hi: 'रात के भोजन पर पूछें: "आरव, यदि 1 किग्रा सेब ₹120.50 का है, तो 2.5 किग्रा कितने का होगा?"',
      mr: 'जेवताना विचारा: "आरव, 1 किलो सफरचंद ₹120.50 चे असेल तर 2.5 किलो कितीचे होईल?"',
    },
    {
      en: 'Celebrate his 7-day study streak with high praise for consistency!',
      hi: 'उसके 7-दिवसीय अध्ययन स्ट्रीक की सराहना करें!',
      mr: 'त्याच्या 7-दिवसांच्या सातत्यपूर्ण अभ्यासाबद्दल त्याचे कौतुक करा!',
    },
  ],
};
